name: Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Submodules
      run: git submodule update --init --recursive
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y cmake ninja-build build-essential
    - name: Make Build Directory
      run: mkdir -p build
    - name: Generate CMake Project
      run: (cd build && cmake ../ -G Ninja)
    - name: Build Project
      run: (cd build && ninja)
    - name: Run Unit-Tests
      run: (cd build && ./actions_playground)
