name: Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Submodules
      run: git submodule update --init --recursive
    - name: Install Dependencies
      run: brew install flex bison
    - name: Modify PATH
      run: export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
    - name: Print Flex Bison Versions
      run: flex --version && bison --version
    - name: Make Build Directory
      run: mkdir -p build
    - name: Generate CMake Project
      run: (cd build && cmake ../ -G Xcode)
    - name: Build Project
      run: cmake --build build
    - name: Run Unit-Tests
      run: (cd build && ./actions_playground)
